# -- Theme Options --
# These options control how the theme functions and allow you to
# customise the display of your website.
#
# Refer to the theme docs for more details about each of these parameters.
# https://nunocoracao.github.io/blowfish/docs/configuration/#theme-parameters

autoSwitchAppearance = true
colorScheme = "congo"
defaultAppearance = "light"  # valid options: light or dark
defaultBackgroundImage = "img/Building-2025.png"  # used as default for background images
disableImageOptimization = false
disableImageOptimizationMD = false
disableTextInHeader = false
enableCodeCopy = true
enableSearch = true
fingerprintAlgorithm = "sha512"  # Valid values are "sha512" (default), "sha384", "sha256"
highlightCurrentMenuArea = true
mainSections = ["Posts", "About", "Blog", "Activities", "Adventures", "Links", "Gallery", "Resources"]
smartTOC = true
smartTOCHideUnfocusedChildren = true

[article]
# editURL = "https://github.com/username/repo/"
editAppendPath = true
heroStyle = "background"  # valid options: basic, big, background
invertPagination = false
seriesOpened = false
showAuthor = true
showAuthorsBadges = false
showBreadcrumbs = true
showDate = true
# showViews = true
# showLikes = true
showDateUpdated = true
showDraftLabel = true
showEdit = false
showHeadingAnchors = false
showHero = true
showPagination = true
showReadingTime = true
showSummary = true
showTableOfContents = true
showTaxonomies = false
showWordCount = true

[fathomAnalytics]

[firebase]

[footer]
showAppearanceSwitcher = true
# showMenu = true
showCopyright = true
showScrollToTop = true
showThemeAttribution = true

[header]
layout = "fixed"  # valid options: basic, fixed
showMenu = true

[homepage]
cardView = true
cardViewScreenWidth = true
homepageImage = "img/Building-2025.png"  # used in: hero, and card
layout = "background"  # valid options: page, profile, hero, card, background, custom
layoutBackgroundBlur = true  # only used when layout equals background
showMoreLink = false
showMoreLinkDest = "/posts"
# disableHeroImageFilter = true
showRecent = false
showRecentItems = 5

[list]
cardView = false
cardViewScreenWidth = false
groupByYear = true
layoutBackgroundHeaderSpace = false
showBreadcrumbs = false
showCards = true
showSummary = true
showTableOfContents = false

[sitemap]
excludedKinds = []

[taxonomy]
showTermCount = true

[verification]

# google = ""
# bing = ""
# pinterest = ""
# yandex = ""
